source ~/.config/zsh/homebrew.zsh

source ~/.config/zsh/env.zsh

source ~/.config/zsh/theme.zsh

source $ZSH/oh-my-zsh.sh

source ~/.config/zsh/aliases.zsh

source ~/.config/zsh/plugins.zsh

source ~/.config/zsh/vi.zsh

source ~/.config/zsh/fzf.zsh

source ~/.config/zsh/mappping.zsh

