#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

source "$HOME/.config/yabai/scripts/initialization.sh"

# ===== Global Settings ==================================

yabai -m config external_bar all:0:0
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse autofocus
yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_shadow float

yabai -m config window_opacity on
yabai -m config active_window_opacity 0.9
yabai -m config normal_window_opacity 0.8
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# ===== Space Settings ==================================

yabai -m config layout bsp
yabai -m config top_padding 50
yabai -m config bottom_padding 10
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 12

# ===== Rules ==================================

yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advanced)$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="QQ" app="^QQ$" title!="^QQ" manage=off
yabai -m rule --add label="Arc" app="^Arc$" title="^Space.*$" manage=off
yabai -m rule --add app="^Arc$" title="^CatZhang$" manage=off

yabai -m rule --add label="Finder" app="^Finder$" manage=off
yabai -m rule --add label="macfeh" app="^macfeh$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off

yabai -m rule --add app="^(System Settings|Calculator|Karabiner-Elements|QuickTime Player|Snipaste|AppCleaner|CleanMyMac X|kitty|WeChat|ClearVPN|Raycast|Bartender 5|Keka|WezTerm|Quantumult X|Clash Verge|ToDesk)$" manage=off

yabai -m rule --add title="Preferences$" manage=off
yabai -m rule --add title="Settings$" manage=off

# ===== Signals ================================

yabai -m signal --add event=application_front_switched action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=application_hidden action="$HOME/.config/yabai/scripts/auto-focus-to-new-one-when-window-destroyed.sh 2> /dev/null"

yabai -m signal --add event=display_removed action="$HOME/.config/yabai/scripts/initialization.sh"
yabai -m signal --add event=display_added action="$HOME/.config/yabai/scripts/initialization.sh"

yabai -m signal --add event=space_changed action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=window_destroyed action="$HOME/.config/yabai/scripts/auto-focus-to-new-one-when-window-destroyed.sh 2> /dev/null"
yabai -m signal --add event=window_minimized action="$HOME/.config/yabai/scripts/auto-focus-to-new-one-when-window-destroyed.sh 2> /dev/null"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_title_changed action="sketchybar --trigger title_change"

echo "yabai configuration loaded.."
